// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.2
// source: calculator/pb/calculator.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Parameters struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Num1          float32                `protobuf:"fixed32,1,opt,name=num1,proto3" json:"num1,omitempty"`
	Num2          float32                `protobuf:"fixed32,2,opt,name=num2,proto3" json:"num2,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Parameters) Reset() {
	*x = Parameters{}
	mi := &file_calculator_pb_calculator_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Parameters) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Parameters) ProtoMessage() {}

func (x *Parameters) ProtoReflect() protoreflect.Message {
	mi := &file_calculator_pb_calculator_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Parameters.ProtoReflect.Descriptor instead.
func (*Parameters) Descriptor() ([]byte, []int) {
	return file_calculator_pb_calculator_proto_rawDescGZIP(), []int{0}
}

func (x *Parameters) GetNum1() float32 {
	if x != nil {
		return x.Num1
	}
	return 0
}

func (x *Parameters) GetNum2() float32 {
	if x != nil {
		return x.Num2
	}
	return 0
}

type Result struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Res           float32                `protobuf:"fixed32,1,opt,name=res,proto3" json:"res,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Result) Reset() {
	*x = Result{}
	mi := &file_calculator_pb_calculator_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Result) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Result) ProtoMessage() {}

func (x *Result) ProtoReflect() protoreflect.Message {
	mi := &file_calculator_pb_calculator_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Result.ProtoReflect.Descriptor instead.
func (*Result) Descriptor() ([]byte, []int) {
	return file_calculator_pb_calculator_proto_rawDescGZIP(), []int{1}
}

func (x *Result) GetRes() float32 {
	if x != nil {
		return x.Res
	}
	return 0
}

var File_calculator_pb_calculator_proto protoreflect.FileDescriptor

const file_calculator_pb_calculator_proto_rawDesc = "" +
	"\n" +
	"\x1ecalculator/pb/calculator.proto\x12\n" +
	"calculator\"4\n" +
	"\n" +
	"Parameters\x12\x12\n" +
	"\x04num1\x18\x01 \x01(\x02R\x04num1\x12\x12\n" +
	"\x04num2\x18\x02 \x01(\x02R\x04num2\"\x1a\n" +
	"\x06Result\x12\x10\n" +
	"\x03res\x18\x01 \x01(\x02R\x03res2\xe0\x01\n" +
	"\n" +
	"Calculator\x123\n" +
	"\x03Sum\x12\x16.calculator.Parameters\x1a\x12.calculator.Result\"\x00\x123\n" +
	"\x03Mul\x12\x16.calculator.Parameters\x1a\x12.calculator.Result\"\x00\x123\n" +
	"\x03Sub\x12\x16.calculator.Parameters\x1a\x12.calculator.Result\"\x00\x123\n" +
	"\x03Div\x12\x16.calculator.Parameters\x1a\x12.calculator.Result\"\x00B\x11Z\x0f./calculator/pbb\x06proto3"

var (
	file_calculator_pb_calculator_proto_rawDescOnce sync.Once
	file_calculator_pb_calculator_proto_rawDescData []byte
)

func file_calculator_pb_calculator_proto_rawDescGZIP() []byte {
	file_calculator_pb_calculator_proto_rawDescOnce.Do(func() {
		file_calculator_pb_calculator_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_calculator_pb_calculator_proto_rawDesc), len(file_calculator_pb_calculator_proto_rawDesc)))
	})
	return file_calculator_pb_calculator_proto_rawDescData
}

var file_calculator_pb_calculator_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_calculator_pb_calculator_proto_goTypes = []any{
	(*Parameters)(nil), // 0: calculator.Parameters
	(*Result)(nil),     // 1: calculator.Result
}
var file_calculator_pb_calculator_proto_depIdxs = []int32{
	0, // 0: calculator.Calculator.Sum:input_type -> calculator.Parameters
	0, // 1: calculator.Calculator.Mul:input_type -> calculator.Parameters
	0, // 2: calculator.Calculator.Sub:input_type -> calculator.Parameters
	0, // 3: calculator.Calculator.Div:input_type -> calculator.Parameters
	1, // 4: calculator.Calculator.Sum:output_type -> calculator.Result
	1, // 5: calculator.Calculator.Mul:output_type -> calculator.Result
	1, // 6: calculator.Calculator.Sub:output_type -> calculator.Result
	1, // 7: calculator.Calculator.Div:output_type -> calculator.Result
	4, // [4:8] is the sub-list for method output_type
	0, // [0:4] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_calculator_pb_calculator_proto_init() }
func file_calculator_pb_calculator_proto_init() {
	if File_calculator_pb_calculator_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_calculator_pb_calculator_proto_rawDesc), len(file_calculator_pb_calculator_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_calculator_pb_calculator_proto_goTypes,
		DependencyIndexes: file_calculator_pb_calculator_proto_depIdxs,
		MessageInfos:      file_calculator_pb_calculator_proto_msgTypes,
	}.Build()
	File_calculator_pb_calculator_proto = out.File
	file_calculator_pb_calculator_proto_goTypes = nil
	file_calculator_pb_calculator_proto_depIdxs = nil
}
