// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.2
// source: echo/pb/echo.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Msg struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Mess          string                 `protobuf:"bytes,1,opt,name=mess,proto3" json:"mess,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Msg) Reset() {
	*x = Msg{}
	mi := &file_echo_pb_echo_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Msg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Msg) ProtoMessage() {}

func (x *Msg) ProtoReflect() protoreflect.Message {
	mi := &file_echo_pb_echo_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Msg.ProtoReflect.Descriptor instead.
func (*Msg) Descriptor() ([]byte, []int) {
	return file_echo_pb_echo_proto_rawDescGZIP(), []int{0}
}

func (x *Msg) GetMess() string {
	if x != nil {
		return x.Mess
	}
	return ""
}

type Reply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Reply         string                 `protobuf:"bytes,1,opt,name=reply,proto3" json:"reply,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Reply) Reset() {
	*x = Reply{}
	mi := &file_echo_pb_echo_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Reply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Reply) ProtoMessage() {}

func (x *Reply) ProtoReflect() protoreflect.Message {
	mi := &file_echo_pb_echo_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Reply.ProtoReflect.Descriptor instead.
func (*Reply) Descriptor() ([]byte, []int) {
	return file_echo_pb_echo_proto_rawDescGZIP(), []int{1}
}

func (x *Reply) GetReply() string {
	if x != nil {
		return x.Reply
	}
	return ""
}

var File_echo_pb_echo_proto protoreflect.FileDescriptor

const file_echo_pb_echo_proto_rawDesc = "" +
	"\n" +
	"\x12echo/pb/echo.proto\x12\x04echo\"\x19\n" +
	"\x03msg\x12\x12\n" +
	"\x04mess\x18\x01 \x01(\tR\x04mess\"\x1d\n" +
	"\x05reply\x12\x14\n" +
	"\x05reply\x18\x01 \x01(\tR\x05reply2(\n" +
	"\x04Echo\x12 \n" +
	"\x06Repeat\x12\t.echo.msg\x1a\v.echo.replyB\vZ\t./echo/pbb\x06proto3"

var (
	file_echo_pb_echo_proto_rawDescOnce sync.Once
	file_echo_pb_echo_proto_rawDescData []byte
)

func file_echo_pb_echo_proto_rawDescGZIP() []byte {
	file_echo_pb_echo_proto_rawDescOnce.Do(func() {
		file_echo_pb_echo_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_echo_pb_echo_proto_rawDesc), len(file_echo_pb_echo_proto_rawDesc)))
	})
	return file_echo_pb_echo_proto_rawDescData
}

var file_echo_pb_echo_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_echo_pb_echo_proto_goTypes = []any{
	(*Msg)(nil),   // 0: echo.msg
	(*Reply)(nil), // 1: echo.reply
}
var file_echo_pb_echo_proto_depIdxs = []int32{
	0, // 0: echo.Echo.Repeat:input_type -> echo.msg
	1, // 1: echo.Echo.Repeat:output_type -> echo.reply
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_echo_pb_echo_proto_init() }
func file_echo_pb_echo_proto_init() {
	if File_echo_pb_echo_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_echo_pb_echo_proto_rawDesc), len(file_echo_pb_echo_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_echo_pb_echo_proto_goTypes,
		DependencyIndexes: file_echo_pb_echo_proto_depIdxs,
		MessageInfos:      file_echo_pb_echo_proto_msgTypes,
	}.Build()
	File_echo_pb_echo_proto = out.File
	file_echo_pb_echo_proto_goTypes = nil
	file_echo_pb_echo_proto_depIdxs = nil
}
