// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.2
// source: registry/pb/registry.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Empty struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Empty) Reset() {
	*x = Empty{}
	mi := &file_registry_pb_registry_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_registry_pb_registry_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_registry_pb_registry_proto_rawDescGZIP(), []int{0}
}

type IsDone struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Done          bool                   `protobuf:"varint,1,opt,name=done,proto3" json:"done,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IsDone) Reset() {
	*x = IsDone{}
	mi := &file_registry_pb_registry_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IsDone) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IsDone) ProtoMessage() {}

func (x *IsDone) ProtoReflect() protoreflect.Message {
	mi := &file_registry_pb_registry_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IsDone.ProtoReflect.Descriptor instead.
func (*IsDone) Descriptor() ([]byte, []int) {
	return file_registry_pb_registry_proto_rawDescGZIP(), []int{1}
}

func (x *IsDone) GetDone() bool {
	if x != nil {
		return x.Done
	}
	return false
}

type Service struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Ip            string                 `protobuf:"bytes,2,opt,name=ip,proto3" json:"ip,omitempty"`
	Port          string                 `protobuf:"bytes,3,opt,name=port,proto3" json:"port,omitempty"`
	Weight        int32                  `protobuf:"varint,4,opt,name=weight,proto3" json:"weight,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Service) Reset() {
	*x = Service{}
	mi := &file_registry_pb_registry_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Service) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Service) ProtoMessage() {}

func (x *Service) ProtoReflect() protoreflect.Message {
	mi := &file_registry_pb_registry_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Service.ProtoReflect.Descriptor instead.
func (*Service) Descriptor() ([]byte, []int) {
	return file_registry_pb_registry_proto_rawDescGZIP(), []int{2}
}

func (x *Service) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Service) GetIp() string {
	if x != nil {
		return x.Ip
	}
	return ""
}

func (x *Service) GetPort() string {
	if x != nil {
		return x.Port
	}
	return ""
}

func (x *Service) GetWeight() int32 {
	if x != nil {
		return x.Weight
	}
	return 0
}

type ListOfServices struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	List          []*Service             `protobuf:"bytes,1,rep,name=list,proto3" json:"list,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListOfServices) Reset() {
	*x = ListOfServices{}
	mi := &file_registry_pb_registry_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListOfServices) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListOfServices) ProtoMessage() {}

func (x *ListOfServices) ProtoReflect() protoreflect.Message {
	mi := &file_registry_pb_registry_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListOfServices.ProtoReflect.Descriptor instead.
func (*ListOfServices) Descriptor() ([]byte, []int) {
	return file_registry_pb_registry_proto_rawDescGZIP(), []int{3}
}

func (x *ListOfServices) GetList() []*Service {
	if x != nil {
		return x.List
	}
	return nil
}

var File_registry_pb_registry_proto protoreflect.FileDescriptor

const file_registry_pb_registry_proto_rawDesc = "" +
	"\n" +
	"\x1aregistry/pb/registry.proto\x12\bregistry\"\a\n" +
	"\x05Empty\"\x1c\n" +
	"\x06isDone\x12\x12\n" +
	"\x04done\x18\x01 \x01(\bR\x04done\"Y\n" +
	"\aservice\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x0e\n" +
	"\x02ip\x18\x02 \x01(\tR\x02ip\x12\x12\n" +
	"\x04port\x18\x03 \x01(\tR\x04port\x12\x16\n" +
	"\x06weight\x18\x04 \x01(\x05R\x06weight\"7\n" +
	"\x0elistOfServices\x12%\n" +
	"\x04list\x18\x01 \x03(\v2\x11.registry.serviceR\x04list2\xe6\x01\n" +
	"\bregistry\x126\n" +
	"\x0fRegisterService\x12\x11.registry.service\x1a\x10.registry.isDone\x122\n" +
	"\vDropService\x12\x11.registry.service\x1a\x10.registry.isDone\x129\n" +
	"\fListServices\x12\x0f.registry.Empty\x1a\x18.registry.listOfServices\x123\n" +
	"\fUpdateWeight\x12\x11.registry.service\x1a\x10.registry.isDoneB\x0fZ\r./registry/pbb\x06proto3"

var (
	file_registry_pb_registry_proto_rawDescOnce sync.Once
	file_registry_pb_registry_proto_rawDescData []byte
)

func file_registry_pb_registry_proto_rawDescGZIP() []byte {
	file_registry_pb_registry_proto_rawDescOnce.Do(func() {
		file_registry_pb_registry_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_registry_pb_registry_proto_rawDesc), len(file_registry_pb_registry_proto_rawDesc)))
	})
	return file_registry_pb_registry_proto_rawDescData
}

var file_registry_pb_registry_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_registry_pb_registry_proto_goTypes = []any{
	(*Empty)(nil),          // 0: registry.Empty
	(*IsDone)(nil),         // 1: registry.isDone
	(*Service)(nil),        // 2: registry.service
	(*ListOfServices)(nil), // 3: registry.listOfServices
}
var file_registry_pb_registry_proto_depIdxs = []int32{
	2, // 0: registry.listOfServices.list:type_name -> registry.service
	2, // 1: registry.registry.RegisterService:input_type -> registry.service
	2, // 2: registry.registry.DropService:input_type -> registry.service
	0, // 3: registry.registry.ListServices:input_type -> registry.Empty
	2, // 4: registry.registry.UpdateWeight:input_type -> registry.service
	1, // 5: registry.registry.RegisterService:output_type -> registry.isDone
	1, // 6: registry.registry.DropService:output_type -> registry.isDone
	3, // 7: registry.registry.ListServices:output_type -> registry.listOfServices
	1, // 8: registry.registry.UpdateWeight:output_type -> registry.isDone
	5, // [5:9] is the sub-list for method output_type
	1, // [1:5] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_registry_pb_registry_proto_init() }
func file_registry_pb_registry_proto_init() {
	if File_registry_pb_registry_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_registry_pb_registry_proto_rawDesc), len(file_registry_pb_registry_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_registry_pb_registry_proto_goTypes,
		DependencyIndexes: file_registry_pb_registry_proto_depIdxs,
		MessageInfos:      file_registry_pb_registry_proto_msgTypes,
	}.Build()
	File_registry_pb_registry_proto = out.File
	file_registry_pb_registry_proto_goTypes = nil
	file_registry_pb_registry_proto_depIdxs = nil
}
